### ISSUE TITLE
ImportError: cannot import name 'format_date'

### ISSUE THREAD

**Issue by lwm** [rtfd/readthedocs.org#2674]
## Details

* Project URL: http://oidcp.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/oidcp/builds/5089159/
* Read the Docs username (if applicable): decentral1se

## Expected Result

My docs would build.

Here's my [pinned dependency list](https://gitlab.com/lukewm/oidcp/blob/master/deps/docs.txt) which I have configured to install in the 'Advanced Configuration'.

I was able to build on Sphinx 1.5.2, is this an issue with 1.5.3?

## Actual Result

```
 Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/oidcp/envs/latest/bin/sphinx-build", line 11, in <module>
    sys.exit(main())
  File "/home/docs/checkouts/readthedocs.org/user_builds/oidcp/envs/latest/lib/python3.5/site-packages/sphinx/__init__.py", line 51, in main
    sys.exit(build_main(argv))
  File "/home/docs/checkouts/readthedocs.org/user_builds/oidcp/envs/latest/lib/python3.5/site-packages/sphinx/__init__.py", line 61, in build_main
    from sphinx import cmdline
  File "/home/docs/checkouts/readthedocs.org/user_builds/oidcp/envs/latest/lib/python3.5/site-packages/sphinx/cmdline.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "/home/docs/checkouts/readthedocs.org/user_builds/oidcp/envs/latest/lib/python3.5/site-packages/sphinx/application.py", line 38, in <module>
    from sphinx.environment import BuildEnvironment, SphinxStandaloneReader
  File "/home/docs/checkouts/readthedocs.org/user_builds/oidcp/envs/latest/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 33, in <module>
    from sphinx.io import SphinxStandaloneReader, SphinxDummyWriter, SphinxFileInput
  File "/home/docs/checkouts/readthedocs.org/user_builds/oidcp/envs/latest/lib/python3.5/site-packages/sphinx/io.py", line 16, in <module>
    from sphinx.transforms import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/oidcp/envs/latest/lib/python3.5/site-packages/sphinx/transforms/__init__.py", line 18, in <module>
    from sphinx.util.i18n import format_date
ImportError: cannot import name 'format_date'
```

**Comment by humitos** [comment]
Mmm... It's seems to be something else, since I can do that in a local-isolated virtualenv with Sphinx 1.5.3

```
(tmp-33534d18a9c45825) [11:19] humitos: tmp-33534d18a9c45825> python
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sphinx.util.i18n import format_date
>>> import sphinx
>>> sphinx.__version__
'1.5.3'
>>> 
```

and 

```
(tmp-9e048896320f583b) [11:19] humitos: tmp-9e048896320f583b> python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from sphinx.util.i18n import format_date
>>> import sphinx
>>> sphinx.__version__
'1.5.3'
>>> 
```

**Comment by humitos** [comment]
Marking this as a bug since I was able to reproduce it in my local venv without problems.

**Comment by humitos** [comment]
I was able to build the documentation by using my local development instance with docker build. So, it seems to be something related with the server.

Another _idea_ that I have is that it could happen that you env on RTD uses a different version of Sphinx and then you updated it and now there is a conflict with some old `.pyc` files. Maybe we can fix that by doing a *Wipe* of that version and re-build?

@lwm can you try that?

**Comment by lwm** [comment]
> Maybe we can fix that by doing a Wipe of that version and re-build?

That did the trick! Clean build on the go now :beers: 

Thanks for taking a look at this @humitos. Much appreciated.
