### ISSUE TITLE
sphinx build fails with "cannot import name 'TYPE_CHECKING' "

### ISSUE THREAD

**Issue by cokelaer** [rtfd/readthedocs.org#3812]
## Details

* Project URL: sequana.readthedocs.io
* Build URL (if applicable): http://readthedocs.org/projects/bioconvert/builds/6901337/
* Read the Docs username (if applicable): cokelaer

## Expected Result

build with success

## Actual Result

error in the sphinx step with this error message:

```
 python /home/docs/checkouts/readthedocs.org/user_builds/bioconvert/conda/master/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/bioconvert/conda/master/bin/sphinx-build", line 11, in <module>
    load_entry_point('Sphinx==1.7.1', 'console_scripts', 'sphinx-build')()
  File "/home/docs/checkouts/readthedocs.org/user_builds/bioconvert/conda/master/lib/python3.5/site-packages/pkg_resources/__init__.py", line 587, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/bioconvert/conda/master/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2800, in load_entry_point
    return ep.load()
  File "/home/docs/checkouts/readthedocs.org/user_builds/bioconvert/conda/master/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2431, in load
    return self.resolve()
  File "/home/docs/checkouts/readthedocs.org/user_builds/bioconvert/conda/master/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2437, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/docs/checkouts/readthedocs.org/user_builds/bioconvert/conda/master/lib/python3.5/site-packages/sphinx/cmd/build.py", line 13, in <module>
    from typing import TYPE_CHECKING
ImportError: cannot import name 'TYPE_CHECKING' 
```

I have looked around but could find much information. 

Worked locally on a Linux box with Python 3.5 with sphinx 1.7.1 using make clean, make html.
It used to work 3 weeks ago when it broke suddenly. We did not change the configuration file on our side. 

I believe I currently have the same issue with another package called sequana also on RTD.
thanks

**Comment by stsewd** [comment]
The `TYPE_CHECKING` constant is from python 3.5.2. I think rtd is using a lower version.

https://docs.python.org/3.6/library/typing.html#typing.TYPE_CHECKING

**Comment by stsewd** [comment]
And according to Sphinx this is fixed on 1.7.2

> #4725: Sphinx does not work with python 3.5.0 and 3.5.1

http://www.sphinx-doc.org/en/1.7/changes.html#bugs-fixed

See also https://github.com/sphinx-doc/sphinx/issues/4725

**Comment by humitos** [comment]
@stsewd RTD uses Python 3.5.2 in the current Docker image.

@cokelaer your problem is that you are pinning Python 3.5.0 in your conda environment file: https://github.com/biokit/bioconvert/blob/master/environment_rtd.yml#L10 and trying to import `TYPE_CHECKING` from Python 3.5.0

So, in order to use the latest Sphinx you will need to upgrade your Python version. Otherwise, you need to downgrade your Sphinx version.

This is not a problem on RTD itself but in your environment.

**Comment by cokelaer** [comment]
I see.  I will try updating my recipes and let you know the outcome. thanks

**Comment by cokelaer** [comment]
it works. thanks. I'm closing this issue.
