### ISSUE TITLE
BUG: Failure using recenly released sphinxcontrib-napoleon 

### ISSUE THREAD

**Issue by bashtage** [rtfd/readthedocs.org#1164]
I strange error occurs when using the just released sphinxcontrib-napoleon (0.3.1). From the logs:

```
ExtensionError: Could not import extension sphinxcontrib.napoleon (exception: cannot import name functools)

Extension error:
Could not import extension sphinxcontrib.napoleon (exception: cannot import name functools)
```

This seems strange since `functool` is in the standard Python library.  Complete log:

https://readthedocs.org/builds/arch/2353826/

I updated by `requirements.txt` to force `sphinxcontrib-napoleon==0.2.11` which continues to work.  

Working log:

https://readthedocs.org/builds/arch/2353939/

It is also worth noting that the docs build fine on my machine using 0.3.1.

**Comment by tritemio** [comment]
I got the same error here:

https://readthedocs.org/builds/fretbursts/2391743/

**Comment by jlyons871** [comment]
Same error replicated again:

https://readthedocs.org/builds/tax-calculator-test/2416796/

**Comment by jlaura** [comment]
It looks like this could be an issue with the move to sphinx 1.3 and the change from `sphinxcontrib.napoleon` to `sphinx.ext.napoleon`.  Can anyone else verify that a modification to conf.py alleviates this error?

**Comment by bashtage** [comment]
@jlaura This isn't the issue since the log shows `Downloading/unpacking sphinx==1.2.2`

**Comment by jlaura** [comment]
@bashtage Via travis, I am seeing the same issue in 1.3: https://travis-ci.org/jlaura/pysal/jobs/54258678

Making the change to .ext.napoleon then results in:

```
sphinx-build -Q -b pickle -d build/doctrees   source build/pickle
Exception occurred:
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/sphinx/domains/python.py", line 95, in make_xref
    result[0][0] = nodes.Text(target[1:])
TypeError: 'Text' object does not support item assignment
The full traceback has been saved in /tmp/sphinx-err-ZWYYoF.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [pickle] Error 1
sphinx-build -b doctest  -d build/doctrees   source build/doctest
Running Sphinx v1.3
making output directory...
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [doctest]: targets for 120 source files that are out of date
updating environment: 120 added, 0 changed, 0 removed
```

It looks like Sphinx is importing without an issue and then throwing another error?

**Comment by bashtage** [comment]
Have you tried `python -c "import functools"` on Travis?  I would assume this works.

**Comment by bashtage** [comment]
I have had some success by deleting by build environment and then POSTing using
https://readthedocs.org/wipe/<PROJECT>/latest/

**Comment by chebee7i** [comment]
I'm getting this now as well.

https://readthedocs.org/builds/dit/2700610/

**Comment by jmagnusson** [comment]
Not having this problem with `sphinxcontrib-napoleon 0.3.9`.

**Comment by agjohnson** [comment]
Seems this was fixed with the Sphinx 1.3.1 update. Reopen this if necessary.

**Comment by jorgehatccrma** [comment]
I'm having a similar issue (minus the functools part). I'm getting this trace:

```
Running Sphinx v1.3.1
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pygrfnn/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pygrfnn/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 143, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pygrfnn/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 433, in setup_extension
    err)
ExtensionError: Could not import extension sphinxcontrib.napoleon (exception: No module named sphinxcontrib.napoleon)

Extension error:
Could not import extension sphinxcontrib.napoleon (exception: No module named sphinxcontrib.napoleon)
```

https://readthedocs.org/projects/pygrfnn/builds/3377520/

Any advice?
